### ISSUE TITLE
Illustrate the use of draft-ietf-core-oscore-edhoc

### ISSUE THREAD

**Issue by malishav** [ace-wg/est-oscore#12]
From John Mattsson's review (https://mailarchive.ietf.org/arch/msg/ace/h85KdNLkMxqzCZjJlY-fGlPEyVw/):

> * Figure 1 does also not illustrate the use of I-D.ietf-core-oscore-edhoc

**Comment by malishav** [comment]
As a reminder, here is the current figure:

```
             +----------------+
             |  EST messages  |
+------------+----------------+
|    EDHOC   |    OSCORE      |
+------------+----------------+
|        CoAP or HTTP         |
+-----------------------------+
```

I am not sure how to better illustrate the combined use of EDHOC and OSCORE in the protocol stack figure. In I-D.ietf-core-oscore-edhoc, EDHOC messages are prepended to the OSCORE messages and transported within CoAP payload. The current figure illustrates that. EST messages in this draft are currently transported as OSCORE payload, which is also depicted in the figure.

Proposal is to add new text:

NEW:
Protocol design also allows that OSCORE and EDHOC messages are carried within the same CoAP message, as per {{I-D.ietf-core-oscore-edhoc}}.

CC: @marco-tiloca-sics

**Comment by marco-tiloca-sics** [comment]
How about this radical redesign of the figure?

```
+------------+----------------+
|    EDHOC   |  EST messages  |
+------------+----------------+
|        CoAP or HTTP         |
|      +----------------------|
|      |        OSCORE        |
+------+----------------------+
```

When using the original EDHOC workflow, you traverse the "stack" as follows:

1. EDHOC message_1 -> CoAP -> wire
2. EDHOC message_2 -> CoAP -> wire
3. EDHOC message_3 -> CoAP -> wire
4. EST messages -> CoAP -> OSCORE -> wire
5. EST messages -> CoAP -> OSCORE -> wire
...

When using the optimized EDHOC workflow, you traverse the "stack" as follows:

1. EDHOC message_1 -> CoAP -> wire
2. EDHOC message_2 -> CoAP -> wire
3. EST messages -> CoAP -> OSCORE + EDHOC message_3 -> wire
4. EST messages -> CoAP -> OSCORE -> wire

**Comment by malishav** [comment]
Thanks @marco-tiloca-sics for the proposal! I am still more in favor of the text addition to the original figure, since the figure is more traditional in terms of the stack "traversal". I am afraid this might cause more confusion than clarity when looked at without an additional explanation. Happy to hear other opinions

CC: @gselander @emanjon

**Comment by gselander** [comment]
I'm fine with the simplified figure with just removed transport.
